stages:
  - py_build

py_build:
  stage: py_build
  image: python:3.6
  script:
    - apt update
    - apt upgrade -q -y
    - pip install -r requirements.txt
    - pip install -r requirements-dev.txt
    - make flake
    - make all-clean
    - make test
